UPDATE questions SET type='multi_choice', choices='["文章のタイトルだけ","登場人物の会話文","「〜である」「〜と考える」などの表現"]' WHERE id=1;
UPDATE questions SET type='multi_choice', choices='["なぜなら","つまり","しかし"]' WHERE id=2;
UPDATE questions SET type='multi_choice', choices='["話題を初めて紹介する段落","具体的な例が多く書かれた段落","筆者の主張やまとめが書かれた段落"]' WHERE id=3;
UPDATE questions SET type='multi_choice', choices='["中心語句","反復語句","キーワード"]' WHERE id=4;
UPDATE questions SET type='multi_choice', choices='["しかし","したがって","つまり"]' WHERE id=5;
UPDATE questions SET type='multi_choice', choices='["10","13","5"]' WHERE id=6;
UPDATE questions SET type='multi_choice', choices='["物語が書かれた年代を調べる","登場人物のセリフや言葉づかいに注目する","登場人物の行動や様子を手がかりにする"]' WHERE id=7;
UPDATE questions SET type='multi_choice', choices='["登場人物の名前が漢字で書かれている","文章が長くなっている","時間・場所・登場人物が変わっている"]' WHERE id=8;
UPDATE questions SET type='multi_choice', choices='["作者が物語を通して読者に伝えたいこと","登場人物の名前と特徴をまとめたもの","物語の中で一番長い場面のこと"]' WHERE id=9;
UPDATE questions SET type='multi_choice', choices='["悔しい（くやしい）／悲しい","悩しい（なやましい）","寂しい（さびしい）"]' WHERE id=10;
UPDATE questions SET type='multi_choice', choices='["登場人物の特徴を読者に伝えるため","登場人物の行動を説明するため","登場人物の気持ち（心情）を表すため"]' WHERE id=11;
UPDATE questions SET type='multi_choice', choices='["150","300","60"]' WHERE id=12;
UPDATE questions SET type='multi_choice', choices='["0","−7","+3"]' WHERE id=13;
UPDATE questions SET type='multi_choice', choices='["+5","+2","−1"]' WHERE id=14;
UPDATE questions SET type='multi_choice', choices='["8","0","−8"]' WHERE id=15;
UPDATE questions SET type='multi_choice', choices='["=",">","<"]' WHERE id=16;
UPDATE questions SET type='multi_choice', choices='["-5","13","-13"]' WHERE id=17;
UPDATE questions SET type='multi_choice', choices='["+3","-17","-3"]' WHERE id=18;
UPDATE questions SET type='multi_choice', choices='["-2","2","-8"]' WHERE id=19;
UPDATE questions SET type='multi_choice', choices='["7","-12","12"]' WHERE id=20;
UPDATE questions SET type='multi_choice', choices='["-3","3","-12"]' WHERE id=21;
UPDATE questions SET type='multi_choice', choices='["−8","6","8"]' WHERE id=22;
UPDATE questions SET type='multi_choice', choices='["a3（a×3 を表したもの）","a×3（そのまま書いたもの）","3a（a×3 を正しく表したもの）"]' WHERE id=23;
UPDATE questions SET type='multi_choice', choices='["x/5","5x","5/x"]' WHERE id=24;
UPDATE questions SET type='multi_choice', choices='["4","3","-3"]' WHERE id=25;
UPDATE questions SET type='multi_choice', choices='["1","11","-1"]' WHERE id=26;
UPDATE questions SET type='multi_choice', choices='["-3xy²","-3x²y","3x²y"]' WHERE id=27;
UPDATE questions SET type='multi_choice', choices='["960","800","840"]' WHERE id=29;
UPDATE questions SET type='multi_choice', choices='["対称","平行","垂直"]' WHERE id=30;
UPDATE questions SET type='multi_choice', choices='["45°","120°","90°"]' WHERE id=31;
UPDATE questions SET type='multi_choice', choices='["対称移動","線対移動","反転移動"]' WHERE id=32;
UPDATE questions SET type='multi_choice', choices='["半直線は両方向に限りなく伸びる","線分は両端があり、長さが定まる","直線は一方向だけに限りなく伸びる"]' WHERE id=33;
UPDATE questions SET type='multi_choice', choices='["110","180","70"]' WHERE id=34;
UPDATE questions SET type='multi_choice', choices='["240","180","120"]' WHERE id=35;
UPDATE questions SET type='multi_choice', choices='["向きと位置","形と大きさ（合同）","位置と大きさ"]' WHERE id=36;
UPDATE questions SET type='multi_choice', choices='["A・I・U・E・O","A・B・C・D・E","A・E・I・O・U"]' WHERE id=37;
UPDATE questions SET type='multi_choice', choices='["G と g","D と b","G と q"]' WHERE id=38;
UPDATE questions SET type='multi_choice', choices='["i am ken.","I am ken.","I am Ken."]' WHERE id=39;
UPDATE questions SET type='multi_choice', choices='["ビー","ベ","ブ"]' WHERE id=40;
UPDATE questions SET type='multi_choice', choices='["P","A","E"]' WHERE id=41;
UPDATE questions SET type='multi_choice', choices='["A・B・C・D・E","A・B・D・C・E","A・C・B・D・E"]' WHERE id=42;
UPDATE questions SET type='multi_choice', choices='["i","I","My"]' WHERE id=43;
UPDATE questions SET type='multi_choice', choices='["20","21","22"]' WHERE id=44;
UPDATE questions SET type='multi_choice', choices='["am","is","are"]' WHERE id=45;
UPDATE questions SET type='multi_choice', choices='["is","are","am"]' WHERE id=46;
UPDATE questions SET type='multi_choice', choices='["彼は先生ですか？","彼は先生ではありません。","彼は先生です。"]' WHERE id=47;
UPDATE questions SET type='multi_choice', choices='["I aren''t hungry.","I isn''t hungry.","I''m not hungry."]' WHERE id=48;
UPDATE questions SET type='multi_choice', choices='["They not are busy.","They are not busy.","They do not busy."]' WHERE id=49;
UPDATE questions SET type='multi_choice', choices='["I are Kenji.","I is Kenji.","I am Kenji."]' WHERE id=50;
UPDATE questions SET type='multi_choice', choices='["Are you from Japan?","Are you from Japan.","Do you from Japan?"]' WHERE id=51;
UPDATE questions SET type='multi_choice', choices='["No, he isn''t.","No, she isn''t.","No, she doesn''t."]' WHERE id=52;
UPDATE questions SET type='multi_choice', choices='["is","am","are"]' WHERE id=53;
UPDATE questions SET type='multi_choice', choices='["2","3","4"]' WHERE id=54;
UPDATE questions SET type='multi_choice', choices='["am","are","play"]' WHERE id=55;
UPDATE questions SET type='multi_choice', choices='["I am like music.","I like music.","Do I like music."]' WHERE id=56;
UPDATE questions SET type='multi_choice', choices='["You do play tennis?","Do you play tennis?","Are you play tennis?"]' WHERE id=57;
UPDATE questions SET type='multi_choice', choices='["I am not play soccer.","I not play soccer.","I don''t play soccer."]' WHERE id=58;
UPDATE questions SET type='multi_choice', choices='["No, I doesn''t.","No, I don''t.","No, I am not."]' WHERE id=59;
UPDATE questions SET type='multi_choice', choices='["I don''t study English every day.","I don''t studied English every day.","I doesn''t study English every day."]' WHERE id=60;
UPDATE questions SET type='multi_choice', choices='["Do you like cats?","Are you like cats?","Do you likes cats?"]' WHERE id=61;
UPDATE questions SET type='multi_choice', choices='["doesn''t","not","don''t"]' WHERE id=62;
UPDATE questions SET type='multi_choice', choices='["2","3","4"]' WHERE id=63;
UPDATE questions SET type='multi_choice', choices='["You are from Tokyo?","Are you from Tokyo?","Do you from Tokyo?"]' WHERE id=64;
UPDATE questions SET type='multi_choice', choices='["isn''t","don''t","doesn''t"]' WHERE id=65;
UPDATE questions SET type='multi_choice', choices='["Yes, he does.","Yes, I do.","Yes, he is."]' WHERE id=66;
UPDATE questions SET type='multi_choice', choices='["Do ／ studies","Do ／ study","Does ／ study"]' WHERE id=67;
UPDATE questions SET type='multi_choice', choices='["He isn''t a doctor.","He isn''t doctor.","He aren''t a doctor."]' WHERE id=68;
UPDATE questions SET type='multi_choice', choices='["Are Ken and Yuki good friend?","Are Ken and Yuki good friends?","Is Ken and Yuki good friends?"]' WHERE id=69;
UPDATE questions SET type='multi_choice', choices='["My father doesn''t watches TV at night.","My father don''t watch TV at night.","My father doesn''t watch TV at night."]' WHERE id=70;
UPDATE questions SET type='multi_choice', choices='["3","2","4"]' WHERE id=71;
UPDATE questions SET type='multi_choice', choices='["2つの孔辺細胞に囲まれており、水蒸気や気体の出入り口になっている","光合成を直接行う場所であり、葉緑体は含まない","葉の表側にのみ存在し、常に開いている"]' WHERE id=72;
UPDATE questions SET type='multi_choice', choices='["光合成で作られた糖","水と無機塩類","酸素と二酸化炭素"]' WHERE id=73;
UPDATE questions SET type='multi_choice', choices='["双子葉類の維管束は輪状に並び、単子葉類の維管束は散在する","どちらも維管束は輪状に並ぶが、道管と師管の位置が逆である","単子葉類の維管束は輪状に並び、双子葉類の維管束は散在する"]' WHERE id=74;
UPDATE questions SET type='multi_choice', choices='["水と二酸化炭素","水と酸素","光と二酸化炭素"]' WHERE id=75;
UPDATE questions SET type='multi_choice', choices='["気孔","根毛","根端"]' WHERE id=76;
UPDATE questions SET type='multi_choice', choices='["5000","10000","4000"]' WHERE id=77;
UPDATE questions SET type='multi_choice', choices='["空気","エタノール","食塩水"]' WHERE id=78;
UPDATE questions SET type='multi_choice', choices='["融点","凝固点","沸点"]' WHERE id=79;
UPDATE questions SET type='multi_choice', choices='["溶ける","浮く","沈む"]' WHERE id=80;
UPDATE questions SET type='multi_choice', choices='["密度","濃度","重度"]' WHERE id=81;
UPDATE questions SET type='multi_choice', choices='["蒸留","分留","蒸発"]' WHERE id=82;
UPDATE questions SET type='multi_choice', choices='["0.78","7.8","780"]' WHERE id=83;
UPDATE questions SET type='multi_choice', choices='["7.4","54","54.7"]' WHERE id=84;
UPDATE questions SET type='multi_choice', choices='["アフリカ大陸","ユーラシア大陸","北アメリカ大陸"]' WHERE id=85;
UPDATE questions SET type='multi_choice', choices='["エジンバラ","ロンドン","マンチェスター"]' WHERE id=86;
UPDATE questions SET type='multi_choice', choices='["約50%","約70%","約30%"]' WHERE id=87;
UPDATE questions SET type='multi_choice', choices='["経度","標高","緯度"]' WHERE id=88;
UPDATE questions SET type='multi_choice', choices='["インド洋","南極海","北極海"]' WHERE id=89;
UPDATE questions SET type='multi_choice', choices='["9","10","8"]' WHERE id=90;
UPDATE questions SET type='multi_choice', choices='["オーストラリア大陸","ユーラシア大陸","北アメリカ大陸"]' WHERE id=91;
UPDATE questions SET type='multi_choice', choices='["111","222","400"]' WHERE id=92;
UPDATE questions SET type='multi_choice', choices='["チグリス川・ユーフラテス川","ナイル川","インダス川"]' WHERE id=93;
UPDATE questions SET type='multi_choice', choices='["国家の形成","文字の発明","鉄器の使用"]' WHERE id=94;
UPDATE questions SET type='multi_choice', choices='["甲骨文字","くさび形文字","象形文字（ヒエログリフ）"]' WHERE id=95;
UPDATE questions SET type='multi_choice', choices='["狩猟・採集","狩猟・栽培","漁労・採集"]' WHERE id=96;
UPDATE questions SET type='multi_choice', choices='["大河の流域は土地が肥えて農業に適しており、食料が豊富に得られたため人口が増加し、都市や国家が発展したから。","大河の流域は農業に必要な水が豊富で作物が育ちやすく、食料を求めて各地から人口が集まり、交易や文化が生まれたから。","大河の流域では農業用の水を確保するために人口が協力して働く必要があり、その組織的な活動をまとめる指導者が現れたから。"]' WHERE id=97;
UPDATE questions SET type='multi_choice', choices='["10000","3000","5000"]' WHERE id=98;
